# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: James McConnell
email: jamesjmcconnell@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Well. Finally got around to putting this old website together. 
  Neat thing about it - powered by [Jekyll](http://jekyllrb.com) 
  and I can use Markdown to author my posts. It actually is a lot 
  easier than I thought it was going to be.
baseurl: "/Welcome" # the subpath of your site, e.g. /blog
url: "http://jamesjmcconnell.github.io" # the base hostname & protocol for your site
github_username:  jamesjmcconnell

# Build settings
markdown: kramdown
